name: Create Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch run test:test
      - name: Build dist
        run: hatch build
      - name: Publish on PyPI
        if: github.ref == 'refs/heads/main'
        run: hatch publish
