name: build hatchling

on:
  push:
    tags:
    - tecton-v*

jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Set Release version
      run: hatch version release

    - name: Build source distribution
      run: python -m build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: /dist
        if-no-files-found: error

  publish:
    name: publish
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Add assets to current release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        # TODO point this to real pypi once we are confident the pipeline works
        repository-url: https://test.pypi.org/legacy/
